routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'MainController@index')->name('index');
Auth::routes();
// servers functions routes
Route::resource('servers', 'ServerController');
Route::get('/table', 'MainController@serversTable')->name('severstable');
// api routes
Route::get('/getServers', 'MainController@getServers');
Route::get('/checkServer', 'MainController@apiServers');

app/Server.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Server extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'name', 'url', 'status'
    ];

    public function logs()
    {
        return $this->hasMany('App\ServerLog', 'server_id', 'id');
    }
}

app/ServerLog.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class ServerLog extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'status', 'date', 'server_id'
    ];

    public function server()
    {
        return $this->belongsTo('App\Server');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/MainController.php
<?php

namespace App\Http\Controllers;

use App\Server;
use App\ServerLog;
use App\Charts\Servers;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class MainController extends Controller
{
  public function __construct()
  {
      $this->middleware('auth');
  }

  public function color_rand() {
    return sprintf('#%06X', mt_rand(0, 0xFFFFFF));
  }

  public function index()
  {
      if (Auth::id())
      {
        $servers = Server::all();
        $labels = ['Not Found', 'Conflict', 'Internal Server Error'];
        $chart = new Servers;
        $chart->labels($labels);

        foreach($servers as $server)
        {
          $color = $this->color_rand();
          $error404 = $server->logs()->where('status', 'Not Found')->count();
          $error409 = $server->logs()->where('status', 'Conflict')->count();
          $error500 = $server->logs()->where('status', 'Internal Server Error')->count();
          $data = [$error404, $error409, $error500];
          $chart->dataset($server->name, 'line', $data)->options([
            'borderColor' => $color,
          ]);
        }
        //dd($chart);

        return view('dashboard/dashboard')->with(['chart' => $chart]);
      }
      else
      {
          return view('auth/login');
      }
  }

  public function serversTable(){
    $servers = Server::get();
    return view('servers/table')->with([
      'servers' => $servers
    ]);
  }

  public function getServers()
  {
    $servers = Server::get();
    return $servers->toJson();
  }

  public function apiServers(Request $request)
  {
    $res = $this->responseServer();
    if($res == 404) {
      $status = 'Not Found';
    }
    else if($res == 409) {
      $status = 'Conflict';
    }
    else if($res == 500) {
      $status = 'Internal Server Error';
    }
    else {
      $status = 'Active';
    }

    $serverLog = new ServerLog();
    $serverLog->server_id = $request->id;
    $serverLog->status = $status;
    $serverLog->save();

    $server = Server::find($request->id);
    $server->update(['status' => $status]);

    return route('severstable');
  }

  public function responseServer(){
    $responses = [200, 200, 200, 200, 200, 200, 200, 404, 409, 500];
    $res = $responses[mt_rand(0, 9)];
    return $res;
  }
}

app/Http/Controllers/ServerController.php
<?php

namespace App\Http\Controllers;

use App\Server;
use App\ServerLog;
use Illuminate\Http\Request;

class ServerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      // $servers = Server::get();
      // return view('servers/index')->with([
      //   'servers' => $servers
      // ]);
      return view('servers/index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      return view('servers/form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      try{
        $server = Server::create($request->all());
        $message = 'Servidor creado exitosamente';
        $status = 'success';
      }
      catch(\Exception $e)
      {
        $message = 'Error al crear servidor, comuníquese con el administrador';
        $status = 'danger';
      }

      $servers = Server::get();
      return view('servers/index')->with([
        'servers' => $servers,
        'status' => $status,
        'message' => $message
      ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Server  $server
     * @return \Illuminate\Http\Response
     */
    public function show(Server $server)
    {
        $logs = ServerLog::where('server_id', $server->id)->paginate(7);
        return view('servers/logs')->with([
            'server' => $server,
            'logs' => $logs
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Server  $server
     * @return \Illuminate\Http\Response
     */
    public function edit(Server $server)
    {
        return view('servers/form')->with([
          'method' => 'PATCH',
          'server' => $server
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Server  $server
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Server $server)
    {
      dd('hola');
      try{
        $server::update($request->all());
        $message = 'Servidor editado exitosamente';
        $status = 'success';
      }
      catch(\Exception $e)
      {
        $message = 'Error al editar servidor, comuníquese con el administrador';
        $status = 'danger';
      }

      $servers = Server::get();
      return view('servers/index')->with([
        'servers' => $servers,
        'status' => $status,
        'message' => $message
      ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Server  $server
     * @return \Illuminate\Http\Response
     */
    public function destroy(Server $server)
    {
      try{
        $server->delete();
        $message = 'Servidor eliminado exitosamente';
        $status = 'success';
      }
      catch(\Exception $e)
      {
        $message = 'Error al eliminar servidor, comuníquese con el administrador';
        $status = 'danger';
      }

      $servers = Server::get();
      return view('servers/index')->with([
        'servers' => $servers,
        'status' => $status,
        'message' => $message
      ]);
    }
}

resources/views/dashboard/dashboard.blade.php
@extends('master')
@section('content')
  <section class="hero">
    <div class="hero-body">
      <div class="container">
          <p class="title">Servidores</p>
          <p class="subtitle">Estadística</p>
      </div>
    </div>
  </section>
  <div class="section is-content">
    {!! $chart->container() !!}
  </div>
@endsection
@section('scripts')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js" charset="utf-8"></script>
  {!! $chart->script() !!}
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- CSRF Token -->
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }} {{ app()->version() }}</title>

        <!-- Styles -->
        <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    </head>
    <body>
        <div id="app">
            <nav class="navbar has-shadow">
                <div class="container">
                    <div class="navbar-brand">
                        <a href="{{ url('/') }}" class="navbar-item">{{ config('app.name', 'Laravel') }}</a>

                        <div class="navbar-burger burger" data-target="navMenu">
                            <span></span>
                            <span></span>
                            <span></span>
                        </div>
                    </div>

                    <div class="navbar-menu" id="navMenu">
                        <div class="navbar-start"></div>

                        <div class="navbar-end">
                            @if (Auth::guest())
                                <a class="navbar-item " href="{{ route('login') }}">Login</a>
                                <a class="navbar-item " href="{{ route('register') }}">Register</a>
                            @else
                                <div class="navbar-item has-dropdown is-hoverable">
                                    <a class="navbar-link" href="#">{{ Auth::user()->name }}</a>

                                    <div class="navbar-dropdown">
                                        <a class="navbar-item" href="{{ route('logout') }}"
                                           onclick="event.preventDefault();document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                              style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </div>
                                </div>
                            @endif
                        </div>
                    </div>
                </div>
            </nav>
            @yield('content')
        </div>

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}"></script>
    </body>
</html>

resources/views/master.blade.php
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <meta name="csrf-token" content="{{ csrf_token() }}">
  <title>Risorse | Reports</title>
  <!-- Styles -->
  <link href="{{ asset('css/app.css') }}" rel="stylesheet">
  <link href="{{ asset('css/main.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar has-shadow">
            <div class="container">
                <div class="navbar-brand">
                    <a class ="navbar-item" href="{{ url('/') }}">
                      <img src="{{ asset('images/agrosty.png') }}">
                    </a>
                    <div class="navbar-burger burger" data-target="menu-toggle">
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>
                </div>
                <div class="navbar-menu" id="menu-toggle">
                    <div class="navbar-start">
                        <a class="navbar-item is-tab is-hidden-tablet">
                            <span class="icon"><i class="fa fa-home"></i></span> Inicio
                        </a>
                        <a href="/servers" class="navbar-item is-tab is-hidden-tablet">
                            <span class="icon"><i class="fa fa-server"></i></span> Servidores
                        </a>
                    </div>
                    <div class="navbar-end">
                        <div class="navbar-item has-dropdown is-hoverable">
                            <a class="navbar-link" href="#">{{ Auth::user()->name }}</a>
                            <div class="navbar-dropdown">
                                <a class="navbar-item" href="{{ route('logout') }}"
                                    onclick="event.preventDefault();document.getElementById('logout-form').submit();">
                                    Logout
                                </a>
                                <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                        style="display: none;">
                                    {{ csrf_field() }}
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </nav>
        <section class=" columns is-fullheight">
            {{-- side menu --}}
            <aside class="main-menu column is-2 is-narrow-mobile is-fullheight section is-hidden-mobile menu">
                <ul class="menu-list">
                    <li>
                        <a href="/" class="home">
                        <span class="icon"><i class="fa fa-home"></i></span> Inicio
                        </a>
                    </li>
                    <li>
                        <a href="/servers" class="reportes">
                            <span class="icon"><i class="fa fa-server"></i></span> Servidores
                        </a>
                    </li>
                </ul>
            </aside>
            {{-- Work area --}}
            <div class="container column is-10">
                    @yield('content')
            </div>
        </section>
    </div>

  <!-- Scripts -->
  <script src="{{ mix('js/app.js') }}"></script>
  <script src="{{ asset('js/main.js') }}"></script>
  <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  @yield('scripts')
</body>
</html>

resources/views/servers/form.blade.php
@extends('master')
@section('content')
    <section class="hero">
        <div class="hero-body">
            <div class="container">
                <p class="title">Servidores</p>
                <p class="subtitle">{{ empty($server)?'Crear nuevo':'Editar' }} servidor</p>
                <nav class="breadcrumb" aria-label="breadcrumbs">
                    <ul>
                        <li></li>
                        <li><a href="/">Inicio</a></li>
                        <li><a href="{{ route('servers.index') }}">Servidores</a></li>
                        <li class="is-active"><a href="#">{{ empty($server)?'Crear nuevo':'Editar' }} servidor</a></li>
                    </ul>
                </nav>
            </div>
        </div>
    </section>
    <div class="section">
        <div class="columns">
            <div class="column is-four-fifths">
              <form method="{{ empty($method) ? 'POST' : $method}}" action="{{ empty($method) ? route('servers.store') : route('servers.update', ['server' => $server]) }}">
                    @csrf
                    <div class="field is-horizontal">
                        <div class="field-label is-normal">
                            <label class="label">Nombre</label>
                        </div>
                        <div class="field-body">
                            <div class="field">
                                <div class="control">
                                    <input class="input" type="text" name="name" value="{{ empty($server)?'':$server->name }}" required>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="field is-horizontal">
                        <div class="field-label is-normal">
                            <label class="label">URL: </label>
                        </div>
                        <div class="field-body">
                            <div class="field">
                                <div class="control">
                                  <input class="input" type="url" name="url" value="{{ empty($server)?'':$server->url }}" required>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="field is-horizontal">
                        <div class="field-label"></div>
                        <div class="field-body">
                            <div class="field is-grouped">
                                <div class="control">
                                    <input type="submit" class="button is-link" value="Aceptar">
                                </div>
                                @if(empty($server))
                                  <div class="control">
                                    <input type="reset" class="button is-text" value="Cancelar">
                                  </div>
                                @else
                                  <div class="control">
                                    <a href="{{ route('servers.index') }}" class="button is-text">Cancelar</a>
                                  </div>
                                @endif
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="column"></div>
        </div>
    </div>
@endsection

resources/views/servers/index.blade.php
@extends('master')
@section('content')
    <section class="hero">
        <div class="hero-body">
            <div class="container">
                <p class="title">Servidores</p>
                <p class="subtitle">Lista de Servidores</p>
                <nav class="breadcrumb" aria-label="breadcrumbs">
                        <ul>
                            <li style="display:none"></li>
                            <li><a href="/">Inicio</a></li>
                            <li class="is-active"><a href="servers">Servidores</a></li>
                        </ul>
                    </nav>
            </div>
        </div>
    </section>
    <div class="section is-content">
        <div class="columns">
            <div class="column is-four-fifths"></div>
            <div class="column">
                <a class="button is-link" href="{{ route('servers.create') }}"><i class="fa fa-plus"></i> &nbsp; Nuevo</a>
            </div>
        </div>
        @if (!empty($message))
            <div class="notification is-{{ $status }}">
                <button class="delete"></button>
                <p>{{ $message }}</p>
            </div>
        @endif
        <div class="servers-table">
          @include('servers/table')
        </div>
    </div>
@endsection

resources/views/servers/logs.blade.php
@extends('master')
@section('content')
  <section class="hero">
    <div class="hero-body">
      <div class="container">
        <p class="title">Servidores</p>
        <p class="subtitle">{{ $server->name }}</p>
        <nav class="breadcrumb" aria-label="breadcrumbs">
          <ul>
            <li style="display:none"></li>
            <li><a href="/">Inicio</a></li>
            <li><a href="/servers">Servidores</a></li>
            <li class="is-active">{{ $server->name }}</li>
          </ul>
        </nav>
      </div>
    </div>
  </section>
  <div class="section is-content">
    <table class="table is-striped">
      <thead>
        <th>Estatus</th>
        <th>Última revisión</th>
      </thead>
      <tbody>
        @if (!empty($logs))
          @foreach ($logs as $log)
            <tr>
              <td><span class="{{ ($log->status == 'Active') ? 'tag is-success' : 'tag is-danger' }}">{{ $log->status }}</span></td>
              <td>{{ $log->created_at }}</td>
            </tr>
          @endforeach
        @else
          <tr>
              <td colspan="4">No hay registros.</td>
          </tr>
        @endif
      </tbody>
    </table>
    {{ $logs->links() }}
  </div>
@endsection

resources/views/servers/table.blade.php
<table class="table is-striped">
    <thead>
        <th>Nombre</th>
        <th>URL</th>
        <th>Estatus</th>
        <th>Última revisión</th>
        <th></th>
        <th></th>
        <th></th>
    </thead>
    <tbody>
        @if (!empty($servers))
            @foreach ($servers as $server)
                <tr>
                    <td>{{ $server->name }}</td>
                    <td>{{ $server->url }}</td>
                    <td><span class="{{ ($server->status == 'Active' || $server->status == 'active') ? 'tag is-success' : 'tag is-danger' }}">{{ $server->status }}</span></td>
                    <td>{{ empty($server->updated_at) ? $server->created_at : $server->updated_at }}</td>
                    <td>
                      <a href="{{ route('servers.show', ['server'=>$server]) }}" class="is-info">
                        <i class="fa fa-eye"></i>
                      </a>
                    </td>
                    <td>
                        <a href="{{ route('servers.edit', ['server'=>$server]) }}" class="is-edit">
                            <i class="fa fa-edit"></i>
                        </a>
                    </td>
                    <td>
                        {!! Form::open(['url' => route('servers.destroy', ['server'=>$server]), 'method' => 'delete']) !!}
                            {{ Form::token() }}
                            {{ Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn is-delete'] )  }}
                        {!! Form::close() !!}
                    </td>
                </tr>
            @endforeach
        @else
            <tr>
                <td colspan="4">No hay servidores registrados.</td>
            </tr>
        @endif
    </tbody>
</table>